export type Feature = {
  slug: string; name: string; eyebrow: string; headline: string; intro: string;
  challenge: string; answer: string; steps: [string, string][]; visual: string;
  heroImage: string; detailImage: string; secondaryImage: string; caseStudy: string; proof: [string, string, string];
  connections: [string, string][]; control: string; outcome: string;
  stepDetails: [string, string, string]; caseDetail: string; connectedDetail: string;
};

export const features: Feature[] = [
  {
    slug: 'property-project-management', name: 'Property & Project Management', eyebrow: 'Turner 10 Property Management ERP',
    headline: 'Keep every project detail within reach.',
    intro: 'See project plans, plot availability, ownership, sales, and finances together in one workspace.',
    challenge: 'As a development grows, inventory, pricing, and project activity can drift into separate records.',
    answer: 'Turner 10 connects project structure to plots, commercial rules, and sales activity, so teams work from the same current context.',
    steps: [['Structure the project', 'Set up phases, blocks, plot dimensions, and commercial rules.'], ['Manage inventory', 'Keep availability, reservations, and sold status visible.'], ['Move with confidence', 'Give assigned teams the project context they need.']],
    visual: 'One platform for multiple projects, accurate property records, and stronger operational control.',
    caseStudy: 'Project setup brings phases, blocks, plot dimensions, pricing, and the plot sales desk into the same workspace. The property record is the starting point for the sales and financial activity that follows.',
    proof: ['Phases and blocks', 'Plot inventory and pricing', 'Project-aware team access'],
    connections: [['Project setup', 'Phases and blocks establish the structure used by every team.'], ['Plot inventory', 'Status and pricing sit with each plot, where sales decisions begin.'], ['Sales desk', 'The team acts from the current project and property record.']],
    control: 'Project assignments limit which property records each team member can manage.',
    outcome: 'Leaders can see the portfolio, plot position, and sales activity without reconciling separate spreadsheets.',
    stepDetails: ['Commercial rules are established before plots reach the sales desk.', 'The current state of a plot stays visible as reservations become sales.', 'Assignments give each team a focused view of the same project.'],
    caseDetail: 'This connects the setup work to day-to-day selling: the team can check the dimensions of a plot, price, and availability in the context of its phase and block before progressing a buyer.',
    connectedDetail: 'Sales, project, and leadership teams can follow a property from its original setup to its current commercial position without rebuilding the story in separate files.',
    heroImage: '/features/property-hero.webp', detailImage: '/product-screens/admin.webp', secondaryImage: '/product-screens/workspace.webp',
  },
  {
    slug: 'sales-contracts-installments', name: 'Sales Contracts & Installments', eyebrow: 'Turner 10 Sales Management',
    headline: 'Follow every sale from agreement to final payment.',
    intro: 'Keep the contract, payment schedule, and collection history together for each property.',
    challenge: 'A sale changes over time. Separate schedules and payment records make its true position hard to see.',
    answer: 'Contract activity stays linked to the buyer, property, schedule, and financial consequence of each step.',
    steps: [['Create the agreement', 'Capture the buyer, plot, terms, and installment schedule.'], ['Track collections', 'See receipts and remaining obligations in contract context.'], ['Manage change', 'Handle transfers, cancellations, and resale with a clear record.']],
    visual: 'One connected system for property sales, installments, collections, and customer obligations.',
    caseStudy: 'The case study follows a contract from creation through its installment schedule, receipts, commissions, transfer, cancellation, and resale. Each action remains linked to the property and customer.',
    proof: ['Contract terms', 'Installment schedules', 'Transfers and resale'],
    connections: [['Property', 'The plot and price remain attached to the agreement.'], ['Schedule', 'Installments define the expected collection position.'], ['Receipts', 'Payments and changes stay visible across the contract lifecycle.']],
    control: 'Transfers, cancellations, and resale retain the original contract context and financial consequence.',
    outcome: 'Sales and finance work from the same customer position as a contract moves forward.',
    stepDetails: ['The agreement anchors the buyer and property to the agreed terms.', 'Collections can be compared with the schedule they satisfy.', 'Later changes preserve the earlier contract and payment history.'],
    caseDetail: 'The same contract context carries forward when installments are collected or terms change. That gives sales and finance a shared answer to what is due, what has been received, and what happened before.',
    connectedDetail: 'The customer agreement, collection history, and later transfer or resale can be reviewed together, so the next team starts from the full lifecycle rather than a handoff summary.',
    heroImage: '/features/sales-hero.webp', detailImage: '/product-screens/sales.webp', secondaryImage: '/product-screens/vouchers.webp',
  },
  {
    slug: 'landowner-management', name: 'Landowner Management', eyebrow: 'Turner 10 Land Acquisition Management',
    headline: 'Know where every land agreement stands.',
    intro: 'Review each landowner agreement alongside its allocations, payments, and ledger activity.',
    challenge: 'Land acquisition combines agreements, payments, and allocation decisions that must stay aligned.',
    answer: 'A connected landowner record helps teams see what was agreed, what is due, and how each allocation affects the project.',
    steps: [['Record agreements', 'Keep landowner terms and project context together.'], ['Follow schedules', 'Track planned payments and completed activity.'], ['Review position', 'See distribution and allocation in a clear view.']],
    visual: 'Clear land records. Connected agreements. Traceable financial obligations.',
    caseStudy: 'Landowner contracts, payment schedules, distribution, allocation, and position views share a project context, giving acquisition and finance teams a common record of the commitment.',
    proof: ['Landowner agreements', 'Payment schedules', 'Allocation position'],
    connections: [['Agreement', 'Landowner terms start the acquisition record.'], ['Commitment', 'Payment schedules show what remains due.'], ['Allocation', 'Distribution and position views show how land is assigned.']],
    control: 'Every allocation is reviewed in the context of its project and landowner agreement.',
    outcome: 'Acquisition and finance share a current view of commitments and land position.',
    stepDetails: ['Terms remain attached to the landowner and the relevant project.', 'Scheduled and completed payments can be read side by side.', 'Allocation decisions stay traceable to the underlying commitment.'],
    caseDetail: 'As payments and allocations progress, the agreement remains the reference point. Acquisition can explain the land position while finance can see the obligations that still need attention.',
    connectedDetail: 'Project, acquisition, and finance teams share the same view of each landowner commitment, its payment progress, and the allocation made against it.',
    heroImage: '/features/land-hero.webp', detailImage: '/product-screens/landowners.webp', secondaryImage: '/product-screens/admin.webp',
  },
  {
    slug: 'accounting-vouchers', name: 'Accounting & Vouchers', eyebrow: 'Turner 10 Financial Management',
    headline: 'Understand the source of every financial entry.',
    intro: 'Record receipts, payments, expenses, and vouchers against the right project and account.',
    challenge: 'Finance loses clarity when operational actions and accounting entries are maintained separately.',
    answer: 'A shared posting gate checks balance, project ownership, and ledger context before a financial entry is saved.',
    steps: [['Set the context', 'Use the project chart of accounts and ledger setup.'], ['Post with control', 'Validate balance, ownership, and the linked business record.'], ['Read the position', 'Review ledgers and statements from posted source data.']],
    visual: 'Project-aware accounting built around real property operations.',
    caseStudy: 'A single posting gate validates balance, project ownership, ledger context, and the related business record before a voucher is saved. Ledgers and statements derive from posted entries.',
    proof: ['Shared posting gate', 'Project chart of accounts', 'Derived statements'],
    connections: [['Business action', 'A receipt, payment, or voucher begins with its source record.'], ['Posting gate', 'Balance, ownership, and ledger context are checked before saving.'], ['Reporting', 'Ledgers and statements derive from posted entries.']],
    control: 'The common posting gate prevents entries without valid project and ledger context.',
    outcome: 'The books reflect approved operational activity and support dependable statements.',
    stepDetails: ['Accounts are organized around the project that owns the entry.', 'The posting check catches missing context before it reaches the ledger.', 'Statements follow the entries that were actually posted.'],
    caseDetail: 'Receipts, payments, and vouchers pass through a common check before posting. That links financial reporting back to the operational event and reduces ambiguity when a balance needs investigation.',
    connectedDetail: 'Operations can identify the transaction behind an entry, while finance can move from the same posted record into ledgers and statements with project context intact.',
    heroImage: '/features/accounting-hero.webp', detailImage: '/product-screens/accounts.webp', secondaryImage: '/product-screens/vouchers.webp',
  },
  {
    slug: 'payroll-partners', name: 'Payroll & Partners', eyebrow: 'Turner 10 Workforce & Obligation Management',
    headline: 'Review payroll before it becomes a payment.',
    intro: 'Bring attendance, earnings, deductions, approvals, and staff obligations into the same payroll process.',
    challenge: 'People and partner obligations often sit outside the records used to manage the project.',
    answer: 'Turner 10 keeps payroll and partner activity connected to approvals, liabilities, and the project books.',
    steps: [['Maintain profiles', 'Keep employees and partners organized.'], ['Run and approve', 'Move payroll through review before posting.'], ['See obligations', 'Track resulting liabilities in financial context.']],
    visual: 'One connected system for employees, payroll, partners, and financial obligations.',
    caseStudy: 'Employee profiles, payroll runs, approvals, and liabilities sit alongside partners, commissions, vendors, and investors within the same project-aware finance environment.',
    proof: ['Employee profiles', 'Payroll approval', 'Partner liabilities'],
    connections: [['People', 'Employee and partner profiles keep ownership clear.'], ['Approval', 'Payroll runs move through review before posting.'], ['Liability', 'The resulting obligation remains visible to finance.']],
    control: 'Approvals connect payroll decisions to the resulting project liability.',
    outcome: 'Teams can see people costs and partner commitments alongside the project books.',
    stepDetails: ['Profiles establish who is involved and how they relate to the work.', 'Review keeps a payroll run distinct from a posted obligation.', 'Liabilities remain visible after approval rather than disappearing into a separate file.'],
    caseDetail: 'The workflow brings payroll review and partner commitments into the same project-aware environment. Approvers can see the people behind a run, and finance can see the obligations that follow.',
    connectedDetail: 'Employee costs, commissions, vendor commitments, and investor relationships sit closer to the financial records used to understand the obligations of a project.',
    heroImage: '/features/payroll-hero.webp', detailImage: '/product-screens/employees.webp', secondaryImage: '/product-screens/workspace.webp',
  },
  {
    slug: 'recovery-operations', name: 'Recovery Operations', eyebrow: 'Turner 10 Collections & Recovery',
    headline: 'Give overdue accounts a clear next step.',
    intro: 'See what is due, record each conversation, and keep the next follow-up tied to the customer account.',
    challenge: 'Recovery teams need the full customer position before making the next call or commitment.',
    answer: 'A connected workflow puts commitments and follow-up activity beside the financial record they relate to.',
    steps: [['Understand the account', 'Review contract dues and receipt history.'], ['Record the interaction', 'Capture calls, commitments, and follow-up dates.'], ['Move the case', 'Escalate through the appropriate notice workflow.']],
    visual: 'From upcoming dues to final resolution, keep every recovery action visible and accountable.',
    caseStudy: 'Collection boards combine commitments, call records, and legal-notice workflows with the contract and receipt position. Recovery teams can act on the current customer record.',
    proof: ['Collection boards', 'Call and commitment records', 'Legal-notice workflow'],
    connections: [['Account position', 'Contract dues and receipts show the current balance.'], ['Contact', 'Calls and commitments record the conversation.'], ['Follow-up', 'The next collection or notice action stays on the board.']],
    control: 'A recovery action follows the customer record, including its payment and commitment history.',
    outcome: 'Collectors and managers can see what was promised, what was paid, and what happens next.',
    stepDetails: ['The collector starts with dues and receipts, not an isolated call list.', 'A promise and its follow-up date remain attached to the account.', 'Escalation can use the existing contact and payment history.'],
    caseDetail: 'Collection boards show the account position alongside calls and commitments. The team can distinguish an unpaid amount from an active promise before deciding whether another follow-up or notice is appropriate.',
    connectedDetail: 'Recovery, sales, and finance can read the same contract and receipt history, with each call, commitment, and next action tied to that customer position.',
    heroImage: '/features/recovery-hero.webp', detailImage: '/product-screens/oversight.webp', secondaryImage: '/product-screens/sales.webp',
  },
  {
    slug: 'project-aware-security', name: 'Project-Aware Security', eyebrow: 'Turner 10 Access & Administration',
    headline: 'Give people access to the work they own.',
    intro: 'Set permissions by role and project, then check them when someone takes an action.',
    challenge: 'A role alone cannot explain which project records a person should be able to manage.',
    answer: 'Turner 10 checks both capability and assignment to the active project before allowing a team member to act.',
    steps: [['Define roles', 'Grant capabilities for the work a person performs.'], ['Assign projects', 'Limit activity to the project context they own.'], ['Review activity', 'Use sessions and audit history to understand changes.']],
    visual: 'Access tailored to the user, their role, and the project they are working on.',
    caseStudy: 'Authorization checks both the user capability and assignment to the active project. Sessions, audit records, backup, and restore support accountable administration.',
    proof: ['Roles and capabilities', 'Project assignments', 'Audit and backup'],
    connections: [['Capability', 'The role defines which action a person can perform.'], ['Assignment', 'The active project determines where they can perform it.'], ['Audit', 'Sessions and activity records make changes reviewable.']],
    control: 'Both capability and project assignment must pass before an action is allowed.',
    outcome: 'Teams can work within their assigned projects while administrators retain oversight and recovery tools.',
    stepDetails: ['Capabilities describe the action, rather than granting blanket access.', 'Project assignment narrows where that action is available.', 'Activity remains reviewable through sessions and audit records.'],
    caseDetail: 'An allowed action needs both the right capability and the right active-project assignment. Audit records, sessions, backup, and restore then support administration after access has been granted.',
    connectedDetail: 'Administrators can manage access across projects while individual teams see the records relevant to their assignments and changes remain traceable.',
    heroImage: '/features/security-hero.webp', detailImage: '/product-screens/admin.webp', secondaryImage: '/product-screens/workspace.webp',
  },
];

export const featureBySlug = (slug: string) => features.find((feature) => feature.slug === slug);
